---
- name: Awaiting for CNI loading
  wait_for:
    path: '{{ cni_bin_dir }}/{{ cni_type }}'

- name: Check addons directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ k8s_addons_dir }}'

- name: Cockroach DB
  template:
    src: "{{ item }}"
    dest: "{{ k8s_addons_dir }}/{{ item }}"
  with_items:
    - cockroachdb.yaml

- name: Deploy script for Cockroach DB
  template:
    src: deploy-cockroachdb.sh
    dest: "{{ k8s_addons_dir }}/deploy-cockroachdb.sh"
    mode: 0755

- name: Run deploy script for cockroachdb
  command: "{{ k8s_addons_dir }}/deploy-cockroachdb.sh"
  when: inventory_hostname in k8s_master_hosts[0]
