apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"

  labels:
    app: prometheus
    chart: prometheus-3.1.0
    component: "node-exporter"
    heritage: Tiller
    release: my-release
  name: my-release-prometheus-node-exporter
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app: prometheus
    component: "node-exporter"
    release: my-release
  type: "ClusterIP"
