{% include 'server.yaml' %}


{% include 'alert-manager.yaml' %}


{% include 'node-exporter.yaml' %}


{% include 'push-gateway.yaml' %}


{% include 'kube-state-metrics.yaml' %}


{% include 'blackbox-exporter.yaml' %}


{% include 'grafana.yaml' %}
